### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by olgeni** [nurugger07/inflex#29]
Hi,

Could you please add a tag for 1.4.0 to the repo? It would simplify building packages a bit :)

**Comment by nurugger07** [comment]
Yes, I'll get it out there today. Sorry, I thought I had updated hex :/

**Comment by nurugger07** [comment]
Updated hex. Sorry for the delay :)

**Comment by olgeni** [comment]
Got 1.4.1 now - but I was thinking about the actual git tag, which we use to build FreeBSD ports of stuff :)

**Comment by nurugger07** [comment]
Ah, I can do that too :)

**Comment by olgeni** [comment]
With that, I get notifications when I should update the package :+1:

**Comment by nurugger07** [comment]
Tag created :)

**Comment by olgeni** [comment]
Done :)

https://svnweb.freebsd.org/ports?view=revision&revision=391919

Thanks!
