### ISSUE TITLE
inflex defines functions in my code

### ISSUE THREAD

**Issue by josevalim** [nurugger07/inflex#32]
`inflex` is promoting the anti-pattern of defining functions in my code with `use`. In Elixir, we usually avoid those unless the module is implementing a well defined behaviour (think GenServer). We have also documented this anti-pattern: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel.ex#L3559-L3600

I would just move all the functions to the Inflex module which would then be imported as:

    import Inflex

This is the simplest way because, if I don't want camelize, I can do:

    import Inflex, except: [camelize: 1]

Most Elixir developers know how to use import well. The current inflex implementation puts aside import into its own scheme which generates code into my own module and relies on function indirection with `__using__`. To drive the point home, imagine every time I wanted to use Enum, it defined all Enum functions in my modules.

I don't believe there is a need for a single `__using__` callback in Inflex. They are just functions.

**Comment by josevalim** [comment]
Finally, if you don't want to have all functions in the same module. You can define them in multiple modules and use defdelegate to create a facade in Inflex. There is still no need for `__using__`.

**Comment by nurugger07** [comment]
@josevalim this makes sense. This was/is an older project that should be updated to best practices. I'll take a look at the refactor.

**Comment by iamvery** [comment]
@nurugger07 would you entertain a PR for this? I was speaking with @josevalim, and I think I may have a contribution ready pretty quickly :+1:

**Comment by nurugger07** [comment]
@iamvery PR's are always welcome!

**Comment by iamvery** [comment]
:heart:

**Comment by nurugger07** [comment]
Thanks! Code merged and hex published :)
