### ISSUE TITLE
Ordinalizer

### ISSUE THREAD

**Issue by pjhampton** [nurugger07/inflex#37]
I forked this project mid Dec '15 and turned it into full stack Text Mining / Natural Language Processing library for the Elixir Programming language which is reaching a good place (i think). I built an ordinalizer into it because it simply didn't exist in inflex. 

I am going to make the repo public and push to hex in the coming months but I have decided to now remove the inflector completely in favor of this library. Would you consider / be interested if I submitted a PR to incorporate an ordinalizer into inflex? 

**ordinalize.ex**

```
defmodule Inflector.Ordinalize do
  @moduledoc false

  def ordinalize(number) when is_number(number) do
    cond do
      number in [11, 12, 13, 14] ->
        Integer.to_string(number) <> "th"
      rem(number, 10) == 1 ->
        Integer.to_string(number) <> "st"
      rem(number, 10) == 2 ->
        Integer.to_string(number) <> "nd"
      rem(number, 10) == 3 ->
        Integer.to_string(number) <> "rd"
      true ->
        Integer.to_string(number) <> "th"
    end
  end
end
```

**Comment by nurugger07** [comment]
Sure. Submit the PR and I'll review it.

**Comment by nurugger07** [comment]
Looks good!
