### ISSUE TITLE
Wrong pluralization when there is "people" in the middle of the word

### ISSUE THREAD

**Issue by gabrielpra1** [nurugger07/inflex#73]
The pluralization of the word **personal** is wrong:
```elixir
iex(10)> Inflex.pluralize "personal"
"peopleal"
```

Here, I expected the output to be **personals**.

In my use case, I wanted to translate **personal trainer**, but it finds **people** in the middle and pluralizes that.

```elixir
iex(11)> Inflex.pluralize "personal_trainer"
"peopleal_trainer"
```

I expected the output to be **personal_trainers**.

The same happens when the words are separated by a space:

```elixir
iex(6)> Inflex.pluralize "personal trainer"
"peopleal trainer"
```

**Comment by nurugger07** [comment]
Thanks! The fix has been merged
