### ISSUE TITLE
Parameterize : accents, commas and trailing space remain 

### ISSUE THREAD

**Issue by augnustin** [nurugger07/inflex#74]
```
iex(3)> Inflex.parameterize("Secrétaire, sténo dactylographe ")
"secrétaire,-sténo-dactylographe-"
```

while the expected is:

```
iex(3)> Inflex.parameterize("Secrétaire, sténo dactylographe ")
"secretaire-steno-dactylographe"
```

at least if the objective is to mimic rails' [parameterize](https://apidock.com/rails/ActiveSupport/Inflector/parameterize)'s behavior

**Comment by nurugger07** [comment]
Thanks! The fix has been merged

**Comment by augnustin** [comment]
Great to see that the project is still active. 

In between we have had issue with `String.normalize(:nfd)` which happened to be depreciated in recent versions of Elixir. 

In our project we are now using the following:

```
  def parameterize(string, option\\"-") do
    string
      |> :unicode.characters_to_nfd_binary()
      |> String.replace(~r/[\'’\"\-]/u, " ")
      |> String.replace(~r/[^A-z\s0-9]/u, "")
      |> String.downcase()
      |> String.trim()
      |> String.replace(~r/\s+/, option)
  end
```

In case you want to update. 

Best
