### ISSUE TITLE
Cut new release / tag ?

### ISSUE THREAD

**Issue by fenollp** [nurugger07/inflex#78]
Looks like Hex & Github disagree:

* https://hex.pm/packages/inflex/1.10.0
* https://github.com/nurugger07/inflex/releases/tag/v1.4.1

**Comment by fenollp** [comment]
Is this unmaintained?

**Comment by nurugger07** [comment]
No, it's still maintained but just haven't had time as of late. I'll be looking at issues and cutting a release this week
