### ISSUE TITLE
Request: support for parsing UPPER_SNAKE_CASE

### ISSUE THREAD

**Issue by shanebdavis** [nurugger07/inflex#90]
I expect both of the following to return the same output, but they don't:

```
iex(6)> Inflex.camelize("THIS_IS_IT")  
"THISISIT"
iex(7)> Inflex.camelize("this_is_it")
"ThisIsIt"
```

**Comment by ucwaldo** [comment]
Actually just stumbled over https://hexdocs.pm/elixir/Macro.html#camelize/1 which purposefully does not change the uppercase input at all actually. However, i had the same expectation as you i must admit, and libraries in the wild seem to have different takes on it as well. Some will change and camelize the input, others not
